---
deployment:
  name: "cozy"
jobs:
  install:
    - nats_server
    - router
    - cloud_controller:
        builtin_services:
            - mongodb
    - ccdb
    - health_manager
    - dea
    - mongodb_gateway
    - mongodb_node:
        index: "0"
dea:
    runtimes:
        - node06
